# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b464001a7bf79dfaf725047526b5bd2c5c7da924b6270a0ac247556371728c91b552f1381ffb63397a530988030937f25cc9db8f460363fd0501e5f3e17b38e1

test:
  secret_key_base: 1004749919d56eefa3f915bb60aaf6d2295ae26b3e14b8f821f671633d7865da792f3a18cf4975c2b529d5d0b489d215a5efe6a5d8be9d6b143bbb2e436dd713

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
